### ISSUE TITLE
Nested component using easeljs-react, causes Uncaught Invariant Violation: Invalid hook call, when wrapped in redux connect() function

### ISSUE THREAD

**Issue by piriej** [loilo-inc/easeljs-react#4]
Great idea, thanks for your work on this. I have hit an issue when trying to use anything but simple components relating to redux, am hoping you can assist. Is there a standard issue template to use?

I have nested easeljs-react components. If I attempt to use redux connect function inside the control as follows:
`// ReSharper disable once UnusedLocalImport - Resharper bug.
import Types from "CmsTypes";
import React from "react";
import { bindActionCreators, Dispatch, AnyAction } from "redux";
import { connect } from "react-redux";
import { TextComponent } from "easeljs-react";
import { Text } from "createjs-module";
import {
    getX,
    getY,
    getExactWidth,
    getExactHeight,
    defaultTurnHeight,
    defaultTurnWidth,
    Orientation
} from "../globals";

const mapStateToProps = (state: Types.RootState) => ({
});

const mapDispatchToProps = (dispatch: Dispatch<AnyAction>) =>
    bindActionCreators({
    }, dispatch);

type Props = {
    label: string;
    width?: number;
    height?: number;
    orientation?: Orientation;
};

type State = Props & {
}

type Components = {
    text: Text;
}

const styles = {
    turnTitleFont: "18px Arial",
    titleColor: "#87ceeb",
    shadowColor: "#000000",
}

class TurnTitleComponent extends React.Component<Props, State> {
    state: State;
    components: Components;
    constructor(props: Props) {
        super(props);
        this.state = Object.assign({} as State, props);
        this.components = {} as Components;
    }

    setTextRef = n => this.components.text = n.getPublicInstance();

    componentDidMount() {
        this.styleText();
    }

    styleText = () => {
        const text = this.components.text;
        text.x = getX(text, this.state.orientation === "horizontal");
        text.y = getY(text, this.state.orientation === "vertical");
        text.lineWidth = getExactWidth(text, this.state.width, defaultTurnWidth);
        text.lineHeight = getExactHeight(text, this.state.height, defaultTurnHeight);
    }

    render() {
        return (
            <TextComponent
                ref={this.setTextRef}
                text={this.props.label}
                font={styles.turnTitleFont}
                color={styles.titleColor}
            ></TextComponent>
        );
    }
}

export const TurnTitle = connect(
    mapStateToProps,
    mapDispatchToProps
)(TurnTitleComponent)`

I receive an invariant exception:

`hostReportError.js:4 Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at invariant (https://localhost:44336/static/js/0.chunk.js:81188:19)
    at Object.throwInvalidHookError (https://localhost:44336/static/js/0.chunk.js:94513:7)
    at useMemo (https://localhost:44336/static/js/0.chunk.js:125107:25)
    at ConnectFunction (https://localhost:44336/static/js/0.chunk.js:119625:75)
    at updateFunctionComponent (https://localhost:44336/static/js/0.chunk.js:112600:24)
    at updateSimpleMemoComponent (https://localhost:44336/static/js/0.chunk.js:112544:14)
    at updateMemoComponent (https://localhost:44336/static/js/0.chunk.js:112457:18)
    at beginWork (https://localhost:44336/static/js/0.chunk.js:113607:20)
    at performUnitOfWork (https://localhost:44336/static/js/0.chunk.js:116665:16)
    at workLoop (https://localhost:44336/static/js/0.chunk.js:116706:28)
    at renderRoot (https://localhost:44336/static/js/0.chunk.js:116791:11)
    at performWorkOnRoot (https://localhost:44336/static/js/0.chunk.js:117743:11)
    at performWork (https://localhost:44336/static/js/0.chunk.js:117653:11)
    at performSyncWork (https://localhost:44336/static/js/0.chunk.js:117627:7)
    at requestWork (https://localhost:44336/static/js/0.chunk.js:117482:9)
    at scheduleWork (https://localhost:44336/static/js/0.chunk.js:117274:9)
    at scheduleRootUpdate (https://localhost:44336/static/js/0.chunk.js:117993:7)
    at updateContainerAtExpirationTime (https://localhost:44336/static/js/0.chunk.js:118019:14)
    at Object.updateContainer (https://localhost:44336/static/js/0.chunk.js:118087:14)
    at StageComponentImpl.componentDidUpdate (https://localhost:44336/static/js/0.chunk.js:65168:14)
    at commitLifeCycles (https://localhost:44336/static/js/0.chunk.js:99255:26)
    at commitAllLifeCycles (https://localhost:44336/static/js/0.chunk.js:100799:11)
    at HTMLUnknownElement.callCallback (https://localhost:44336/static/js/0.chunk.js:81278:18)
    at Object.invokeGuardedCallbackDev (https://localhost:44336/static/js/0.chunk.js:81327:20)
    at invokeGuardedCallback (https://localhost:44336/static/js/0.chunk.js:81381:35)
    at commitRoot (https://localhost:44336/static/js/0.chunk.js:101023:11)
    at https://localhost:44336/static/js/0.chunk.js:102571:9
    at Object.unstable_runWithPriority (https://localhost:44336/static/js/0.chunk.js:142071:16)
    at completeRoot (https://localhost:44336/static/js/0.chunk.js:102570:17)
    at performWorkOnRoot (https://localhost:44336/static/js/0.chunk.js:102493:13)
    at performWork (https://localhost:44336/static/js/0.chunk.js:102398:11)
    at performSyncWork (https://localhost:44336/static/js/0.chunk.js:102372:7)
    at batchedUpdates$1 (https://localhost:44336/static/js/0.chunk.js:102599:11)
    at Object.notify (https://localhost:44336/static/js/0.chunk.js:120651:7)
    at Subscription.notifyNestedSubs (https://localhost:44336/static/js/0.chunk.js:120693:20)
    at Provider.notifySubscribers (https://localhost:44336/static/js/0.chunk.js:119462:29)
    at Subscription.handleChangeWrapper (https://localhost:44336/static/js/0.chunk.js:120698:12)
    at Object.dispatch (https://localhost:44336/static/js/0.chunk.js:126201:7)
    at e (<anonymous>:1:40553)
    at https://localhost:44336/static/js/0.chunk.js:125834:22
    at SafeSubscriber.dispatch [as _next] (https://localhost:44336/static/js/0.chunk.js:126600:28)
    at SafeSubscriber.__tryOrUnsub (https://localhost:44336/static/js/0.chunk.js:128285:10)
    at SafeSubscriber.next (https://localhost:44336/static/js/0.chunk.js:128214:14)
    at Subscriber._next (https://localhost:44336/static/js/0.chunk.js:128144:22)
    at Subscriber.next (https://localhost:44336/static/js/0.chunk.js:128113:12)
    at MergeMapSubscriber.notifyNext (https://localhost:44336/static/js/0.chunk.js:134585:22)
    at InnerSubscriber._next (https://localhost:44336/static/js/0.chunk.js:127167:17)
    at InnerSubscriber.Subscriber.next (https://localhost:44336/static/js/0.chunk.js:128113:12)
    at Notification.observe (https://localhost:44336/static/js/0.chunk.js:127227:42)
    at QueueAction.ObserveOnSubscriber.dispatch [as work] (https://localhost:44336/static/js/0.chunk.js:134938:18)`

If I remove redux out of the equation (by exporting the component in place of wrapping it in connect and then exporting) it works fine. Would you have an example of doing this kind of thing?

**Comment by keroxp** [comment]
@piriej thank you for report. But we have not used redux with React so have no idea about it.

And unfortunately, this project is no longer maintained. Previously we've been considering to use easeljs with React for our product but decided not to use for some reasons. 

- Managing VirtualDOM's lifecycle and canvas is messing for high performance canvas application.
- EaselJS's development is calm. ESM is not supported yet. 

We decided to develop an independent canvas library for our product. Sorry.
If you want to make canvas application with React, please consider use well maintained project like react-konva (https://github.com/konvajs/react-konva)

**Comment by piriej** [comment]
Thanks for your response, appreciate your advice.
